services:
    nginx-service:
        image: nginx
        depends_on:
            - certbot
        ports:
            - 80:80
            - 443:433
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        networks:
            - todo-network
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        command: certonly --webroot -w /var/www/certbot --email your@email.com --agree-tos --no-eff-email --staging -d ivanlogvynenko.ddns.net

networks:
    todo-network:
        external: true

volumes:
    certbot:
        driver: local
